version: '3.8'
services:
  streampay:
    image: ghcr.app/streampayment/streampay:latest
    command: all-in-one --skip-config
    env_file:
      - docker.env
    volumes:
      - './tmp:/src/tmp'
    ports: [ '80:80' ]
    networks: [ net-streampay ]
    depends_on: [ postgres ]
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    command: postgres -c log_statement=all
    restart: on-failure
    environment:
      - POSTGRES_DB=streampay
      - POSTGRES_USER=streampay
      - POSTGRES_PASSWORD=streampay
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    ports: [ '5432:5432' ]
    networks: [ net-streampay ]

networks:
  net-streampay:

volumes:
  app-volume:
  pg-data:
